spring:
  devtools:
    restart:
      enabled: false
      additional-exclude: static/**
    livereload:
      enabled: false
    jackson:
      serialization:
        indent-output: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/GFT?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: gft
    password: gft
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    change-log: classpath:config/liquibase/master.xml

  thymeleaf:
    cache: false

  messages:
      basename: env

